version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caja-chica-app
    restart: unless-stopped
    ports:
      - "8080:80"
      - "5173:5173"  # Puerto de Vite para desarrollo
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor  # Volumen anónimo para vendor
      - /var/www/html/node_modules  # Volumen anónimo para node_modules
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_URL=${APP_URL:-http://localhost:8080}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-caja_chica_bap_db}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-123}
    networks:
      - caja-chica-network

  db:
    image: mysql:8.0
    container_name: caja-chica-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-caja_chica_bap_db}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-123}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - caja-chica-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: caja-chica-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=${DB_HOST:-db}
      - PMA_PORT=${DB_PORT:-3306}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-123}
    depends_on:
      - db
    networks:
      - caja-chica-network

networks:
  caja-chica-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local